class TaskType:
    BUILD = "build"
    DEPLOY = "deploy"
    SHELL = "shell"
    SHELL_WRAPPER = "shell-wrapper"
    NOOP = "noop"
    COPY_ANGULAR_DIST = "copy-angular-dist"
    RELEASE_PREPARE = "release/prepare"
    RELEASE_ROLLBACK = "release/rollback"
    RELEASE_COMMIT = "release/commit"
    RELEASE_CLEANUP = "release/cleanup"
