class Const:
    CEDAR_HOME = 'CEDAR_HOME'
    CEDAR_VERSION = 'CEDAR_VERSION'
    CEDAR_RELEASE_VERSION = 'CEDAR_RELEASE_VERSION'
    CEDAR_NEXT_DEVELOPMENT_VERSION = 'CEDAR_NEXT_DEVELOPMENT_VERSION'
    CEDAR_CA_HOME = 'CEDAR_CA_HOME'
    CEDAR_CA_COMMON_NAME = 'CEDAR_CA_COMMON_NAME'

    CEDAR_DEV_USE_PRIVATE_REPOS = 'CEDAR_DEV_USE_PRIVATE_REPOS'
    CEDAR_DEV_BUILD_FRONTENDS = 'CEDAR_DEV_BUILD_FRONTENDS'

    FILE_PACKAGE_JSON = "package.json"
    FILE_PACKAGE_LOCK_JSON = "package-lock.json"
    FILE_POM_XML = "pom.xml"
    FILE_ENV = ".env"
    FILE_DOCKER = "Dockerfile"
    FILE_BIN_IMAGE_BASE = "bin/cedar-images-base.sh"
    FILE_BIN_UTIL_SET_ENV_GENERIC = "bin/util/set-env-generic.sh"
