class Const:
    CEDAR_HOME = 'CEDAR_HOME'
    CEDAR_VERSION = 'CEDAR_VERSION'
    CEDAR_RELEASE_VERSION = 'CEDAR_RELEASE_VERSION'
    CEDAR_NEXT_DEVELOPMENT_VERSION = 'CEDAR_NEXT_DEVELOPMENT_VERSION'
